/**

 * The MSN Messenger profile card: avatar, display status and nickname.

 *

 * Pure logic — no DOM. avatar-ui.js does the rendering, styles.css does the

 * Aero glass. The statuses are the MSN Messenger set (the era's cartoon icons),

 * and there are sixteen avatars because MSN display pictures were a 4x4 grid.

 */



import { versioned } from './build.js?v=2026-10-05-A';



export const SAVE_KEY = 'aero-arcade-profile';

export const DEFAULT_NICK = 'Karin';

export const NICK_MAX = 18;      // MSN nicknames were short; so is the header slot



/**

 * The classic Messenger status list. Colours are deliberately close to the

 * original icons so the muscle memory still works.

 */

export const STATUSES = [

  { id: 'online', label: 'Online', colour: '#2e9e5b', blurb: 'Available' },

  { id: 'busy', label: 'Busy', colour: '#e53935', blurb: 'Do not disturb' },

  { id: 'brb', label: 'Be right back', colour: '#f0b429', blurb: 'Gone for a moment' },

  { id: 'away', label: 'Away', colour: '#4fc3f7', blurb: 'Not at the desk' },

  { id: 'phone', label: 'On the phone', colour: '#d81b60', blurb: 'In a call' },

  { id: 'lunch', label: 'Out to lunch', colour: '#fb8c00', blurb: 'Gone to eat' },

  { id: 'invisible', label: 'Appear offline', colour: '#8d9aa5', blurb: 'Hidden but signed in' },

  { id: 'offline', label: 'Offline', colour: '#5c6b76', blurb: 'Signed out' },

];



export const DEFAULT_STATUS = 'online';



/**

 * Sixteen Aero-glass emblems, in the order they appear in the 4x4 grid. The

 * files are generated by scripts/gen-avatars.mjs and committed, so there is no

 * build step to run before the site works.

 */

export const AVATARS = Array.from({ length: 16 }, (_, i) => ({

  index: i,

  src: versioned(`./assets/avatars/avatar-${String(i + 1).padStart(2, '0')}.svg`),

  label: `Avatar ${i + 1}`,

}));



/* -------------------------------------------------------------- pickers */



/** Path for an avatar index, clamped into range. */

export function avatarSrc(index) {

  return AVATARS[clampAvatarIndex(index)].src;

}



/** Coerce anything into a usable avatar index. */

export function clampAvatarIndex(index) {

  const n = Math.trunc(Number(index));

  if (!Number.isFinite(n)) return 0;

  return Math.min(AVATARS.length - 1, Math.max(0, n));

}



export function statusById(id) {

  return STATUSES.find((s) => s.id === id) ?? STATUSES[0];

}



/* -------------------------------------------------------------- updates */



export function withAvatar(profile, index) {

  return { ...profile, avatarIndex: clampAvatarIndex(index) };

}



export function withStatus(profile, statusId) {

  const known = STATUSES.some((s) => s.id === statusId) ? statusId : DEFAULT_STATUS;

  return { ...profile, statusId: known };

}



export function withNick(profile, nick) {

  const trimmed = String(nick ?? '').trim().slice(0, NICK_MAX);

  return { ...profile, nick: trimmed || DEFAULT_NICK };

}



/* ------------------------------------------------------------ persistence */



export function defaultProfile() {

  return { avatarIndex: 0, statusId: DEFAULT_STATUS, nick: DEFAULT_NICK };

}



/**

 * Read the profile, repairing anything unusable. A blocked or corrupt store

 * must never stop the site rendering, so every failure path falls back to the

 * defaults rather than throwing.

 */

export function loadProfile(storage) {

  const base = defaultProfile();

  let raw = null;

  try {

    raw = storage?.getItem(SAVE_KEY);

  } catch {

    return base;

  }

  if (!raw) return base;



  let saved = null;

  try {

    saved = JSON.parse(raw);

  } catch {

    return base;

  }

  if (!saved || typeof saved !== 'object' || Array.isArray(saved)) return base;



  let profile = base;

  if (Number.isFinite(Number(saved.avatarIndex))) {

    profile = withAvatar(profile, Number(saved.avatarIndex));

  }

  if (typeof saved.statusId === 'string') {

    profile = withStatus(profile, saved.statusId);

  }

  if (typeof saved.nick === 'string') {

    profile = withNick(profile, saved.nick);

  }

  return profile;

}



/** Persist the profile. Silently does nothing if storage is unavailable. */

export function saveProfile(storage, profile) {

  try {

    storage?.setItem(SAVE_KEY, JSON.stringify({

      avatarIndex: profile.avatarIndex,

      statusId: profile.statusId,

      nick: profile.nick,

    }));

    return true;

  } catch {

    return false;

  }

}



/* -------------------------------------------------------------- display */



/**

 * One line of text for the header: "<nick> — <status>" / "<status>".

 * Long nicknames are truncated so the header cannot be pushed around.

 */

export function profileSummary(profile) {

  const status = statusById(profile.statusId).label;

  const nick = String(profile.nick ?? '').trim();

  if (!nick || nick === DEFAULT_NICK) return status;

  const room = NICK_MAX + status.length + 3;

  const shown = nick.length > room ? `${nick.slice(0, room)}…` : nick;

  return `${shown} — ${status}`;

}

